spring:
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
    url: 'jdbc:h2:file:./users-db'
  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api
